In [2]:
from IMPORTS import *

In [12]:
from REINFORCE import Model, RLDataset, REINFORCELightning

In [5]:
env_id = 'CartPole-v1'
env = gym.make(env_id)
obs_size = env.observation_space.shape[0]
n_actions = env.action_space.n
net = Model(obs_size, n_actions)
dataset = RLDataset(net, env)
dataloader = DataLoader(dataset=dataset)

In [10]:
for i_batch, sample_batched in enumerate(dataloader):
    # print(i_batch, sample_batched['image'].size(),
    #       sample_batched['landmarks'].size())
    print(f'num of batch = {i_batch}')
    print(f'len of sample in batch = {len(sample_batched[0])}')
    print('-------------------')
    print(i_batch, sample_batched[0])
    print('-------------------')
    print(i_batch, sample_batched[1])
    print('-------------------')
    print(i_batch, sample_batched[2])
    print('-------------------')
    print(i_batch, sample_batched[3])
    print('-------------------')
#     print(i_batch, sample_batched[4])
#     print('-------------------')

num of batch = 0
len of sample in batch = 21
-------------------
0 [tensor([1.], dtype=torch.float64), tensor([1.], dtype=torch.float64), tensor([1.], dtype=torch.float64), tensor([1.], dtype=torch.float64), tensor([1.], dtype=torch.float64), tensor([1.], dtype=torch.float64), tensor([1.], dtype=torch.float64), tensor([1.], dtype=torch.float64), tensor([1.], dtype=torch.float64), tensor([1.], dtype=torch.float64), tensor([1.], dtype=torch.float64), tensor([1.], dtype=torch.float64), tensor([1.], dtype=torch.float64), tensor([1.], dtype=torch.float64), tensor([1.], dtype=torch.float64), tensor([1.], dtype=torch.float64), tensor([1.], dtype=torch.float64), tensor([1.], dtype=torch.float64), tensor([1.], dtype=torch.float64), tensor([1.], dtype=torch.float64), tensor([1.], dtype=torch.float64)]
-------------------
0 [tensor([-3.9399], dtype=torch.float64), tensor([nan], dtype=torch.float64), tensor([-4.0087], dtype=torch.float64), tensor([nan], dtype=torch.float64), tensor([nan], dtype=to

In [14]:
model = REINFORCELightning(env_id)
model

REINFORCELightning(
  (net): Model(
    (net): Sequential(
      (0): Linear(in_features=4, out_features=16, bias=True)
      (1): ReLU()
      (2): Linear(in_features=16, out_features=8, bias=True)
      (3): ReLU()
      (4): Linear(in_features=8, out_features=2, bias=True)
      (5): Softmax(dim=0)
    )
  )
)

In [73]:
for i_batch, sample_batched in enumerate(dataloader):
#     for state in sample_batched[2]:
#         out = model(state)
#         print(out)
    print(len(sample_batched[2]))
    state = torch.cat(sample_batched[2])
    actions = torch.cat(sample_batched[3])
    print(actions.numpy())
#     print(state)
    print(actions)
    print('---')
    out = model(state)
    print(out)
    print('---')
#     print(out.squeeze(0))
#     probs = out[list(actions.numpy())]
    probs = out.gather(1, actions.unsqueeze(-1)).squeeze(-1)
    print(probs)
    print('---')
    log_probs = torch.log(probs)
    print(log_probs)
    print('---')

23
[1 0 0 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 0 1 0 1 0]
tensor([1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0])
---
tensor([[0.0415, 0.0431],
        [0.0409, 0.0427],
        [0.0415, 0.0431],
        [0.0425, 0.0436],
        [0.0414, 0.0430],
        [0.0424, 0.0436],
        [0.0433, 0.0438],
        [0.0445, 0.0437],
        [0.0433, 0.0438],
        [0.0423, 0.0435],
        [0.0433, 0.0438],
        [0.0446, 0.0437],
        [0.0434, 0.0437],
        [0.0447, 0.0436],
        [0.0435, 0.0437],
        [0.0449, 0.0435],
        [0.0438, 0.0436],
        [0.0427, 0.0436],
        [0.0441, 0.0435],
        [0.0456, 0.0434],
        [0.0445, 0.0434],
        [0.0461, 0.0433],
        [0.0450, 0.0433]], dtype=torch.float64, grad_fn=<SoftmaxBackward>)
---
tensor([0.0431, 0.0409, 0.0415, 0.0436, 0.0414, 0.0424, 0.0433, 0.0437, 0.0438,
        0.0423, 0.0433, 0.0437, 0.0434, 0.0436, 0.0435, 0.0435, 0.0436, 0.0427,
        0.0441, 0.0434, 0.0445, 0.0433, 0.0450], dtype=t

In [46]:
env.action_space.n

2